"""Added Donation and Users

Revision ID: a356f321016c
Revises: 2a0654e02a65
Create Date: 2023-08-12 13:41:32.626088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a356f321016c'
down_revision = '2a0654e02a65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
